import typing

class QObject:
    def __init__(self) -> None: ...

class QUrl:
    @staticmethod
    def fromLocalFile(path: str) -> "QUrl": ...

class _SignalInstance:
    def emit(self, *args: object) -> None: ...

def pyqtSignal(*types: object, **kwargs: object) -> _SignalInstance: ...

def pyqtSlot(
    *types: object, name: typing.Optional[str] = ..., result: typing.Any = ...
) -> typing.Callable[[typing.Any], typing.Any]: ...

# A property descriptor: mypy reads __get__ as the value type and __set__ as
# making the attribute assignable. This matches how PyQt6 registers
# pyqtProperty(type, fget, fset, notify=...) at class-definition time.
class _QtProperty:
    def __get__(self, instance: typing.Any, owner: typing.Optional[type] = ...) -> object: ...
    def __set__(self, instance: typing.Any, value: object) -> None: ...

def pyqtProperty(*args: object, **kwargs: object) -> _QtProperty: ...
