import typing

class QQmlContext:
    def setContextProperty(self, name: str, value: object) -> None: ...

class QQmlApplicationEngine:
    def rootContext(self) -> typing.Optional["QQmlContext"]: ...
    def load(self, url: object) -> None: ...
    def rootObjects(self) -> list[object]: ...
